document joi -> OpenAPI behavior a bit (#35)
* fix wrong parser name and make test pass

In the documentation and the test, this is referred to as 'json-draft-04', and not 'json-draft-4'
Now the `test/json-draft-04.spec.js` test runs.

Note:

There is still an error, I cannot trace immidiately:

```
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
…
```

* add read- and writeOnly properties to fixtures and outputs

except for openapi

* expect read- and writeOnly properties in openapi output

* realize

* document joi -> OpenAPI behavior a bit

- most common cases
- meta annotations